version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: hoanh
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simplebank
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # command: [ "postgres", "-c", "log_statement=all" ]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - postgres
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   networks: 
  #     - mynetwork
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   networks: 
  #     - mynetwork
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 9092:9092
  #   restart: always
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  # kafdrop:
  #   image: obsidiandynamics/kafdrop:latest
  #   networks: 
  #     - mynetwork
  #   depends_on:
  #     - kafka
  #   ports:
  #     - 19000:9000
  #   environment:
  #     KAFKA_BROKERCONNECT: kafka:29092
volumes:
  postgres-data:


# networks:
#   mynetwork:
#     driver: bridge
